CPPFLAGS=-isystem ~/work/math/lib/boost_1.62.0  -isystem ~/work/math -isystem ~/work/math/lib/eigen_3.3.3 -isystem ~/work/math/lib/cvodes_2.9.0/include -std=c++11 -O3
#LDFLAGS=-L$(HOME)/local/lib -lboost_serialization -lboost_mpi
LDFLAGS=$(HOME)/work/math/lib/boost_1.62.0/lib/libboost_serialization.a $(HOME)/work/math/lib/boost_1.62.0/lib/libboost_mpi.a
CXX=mpicxx
