CPPFLAGS=-isystem ~/work/boost_1_62_0  -isystem ~/work/math -isystem ~/work/math/lib/eigen_3.3.3 -isystem ~/work/math/lib/cvodes_2.9.0/include -std=c++11 -O3
LDFLAGS=-L$(HOME)/local/lib -lboost_serialization -lboost_mpi
CXX=mpicxx
