CPPFLAGS=-isystem ~/work/math/lib/boost_1.62.0  -isystem ~/work/math -isystem ~/work/math/lib/eigen_3.3.3 -isystem ~/work/math/lib/cvodes_2.9.0/include -O3 -std=c++11
LDFLAGS=-L$(HOME)/local/lib -lboost_serialization -lboost_mpi
CXX=mpic++
